spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN:https://cupl.netlify.app}
  upload:
    dir: ${UPLOAD_DIR:uploads}
  base-url: ${BASE_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    com.cupl.backend: INFO
